---
app_name: "it-news-bot"
username: dapmoed
docker:
  tag: "latest"
  image: "{{ username }}/{{ app_name }}"
  path_compose: "/opt/{{ app_name }}"
traefik:
  api_host: "api.sloin.ru"
  api_prefix: "/{{ app_name }}"
  network: "traefik-shared"
  le_resolver: "le_resolver"